FROM oven/bun:1

WORKDIR /user/src/app

COPY ./packages  ./packages
COPY ./package.json   ./package.json

COPY ./turbo.json   ./turbo.json
COPY ./bun.lock     ./bun.lock

COPY ./apps/backend   ./apps/backend
COPY packages/db/.env packages/db/.env

RUN bun install
RUN bun run db:generate

EXPOSE 3000

CMD ["bun", "run", "start:backend"]